### ISSUE TITLE
Clubs Outreach

### ISSUE THREAD

**Issue by isss111** [smartcontractresearchforum/operations#146]
**Tasks:**

- [ ] Email 10 groups
- [ ] Email 20 groups
- [ ] Email 30 groups
- [ ] Email 40 groups
- [ ] Email 50 groups
- [ ] Set up calls with those that respond 
- [ ] Research more clubs to add to the list
- [ ] Revise the list of clubs
