### ISSUE TITLE
Event planning

### ISSUE THREAD

**Issue by isss111** [smartcontractresearchforum/operations#148]
**Tasks:**

- [ ] When do we want to do the kickoff 
- [ ] What does the kickoff look like?
- [ ] When do we want to do a second event
- [ ] What does the second event look like?
- [ ] When do we want to do the third event?
- [ ] What does the third event look like? 
- [ ] List people who to reach out to
