### ISSUE TITLE
Coordination and ops

### ISSUE THREAD

**Issue by isss111** [smartcontractresearchforum/operations#149]
**Tasks:**

- [x] Start task tracking 
- [x] Convert this to a github board
- [ ] Where do we send students / where do they signal interest? 
- [ ] Set up calendar invites?
- [ ] Set up form to collect emails?
