### ISSUE TITLE
Project: Open Peer Review Experiment 

### ISSUE THREAD

**Issue by eleventh19** [smartcontractresearchforum/operations#32]
### Project Description

The goal of this project is to explore what an open peer review for independent researchers experiment can look like. This project will entail:

- Identifying independent researchers who want open peer review
- Creating an advisory board to provide input on the experiment 
- Picking what tools to use for version controlled knowledge management 
- Creating a project plan for the initial researchers 
- Finding peer reviewers for the researchers 
- Running the experiment 

### Work Plan

- [x] meet on 3/14 to discuss the project with the team 
- [x] create an initial plan - what is being researcher, next steps for this week, next meetings
- [x] pull together a few peer review processes
- [x] start drafting a v1 SCRF Open Peer Review Process doc 
- [x] share with the core ops team 
- [x] get advisors onboard 
- [x] discuss with advisors 
- [x] refine process
- [ ] find up to 3 independent researchers who want to opt into getting open peer review
- [ ] find 3-6 reviewers depending on the complexity/necessity of interdisciplinary backgrounds 
- [ ] figure out relevant grants 
- [ ] pick tech to use 
- [ ] run trial review with tech 
- [ ] get everyone onboard with the plan 
- [ ] plan start date 
- [ ] start project
- [ ] run open peer review 1
- [ ] run open peer review 2
- [ ] run open peer review 3
- [ ] get final results published on the forum
- [ ] post mortem with researchers
- [ ] post mortem with reviewers
- [ ] post mortem with advisors
- [ ] plan next step
- [ ] close ticket and start new one 

### Resources

- [link to project plan](https://docs.google.com/document/d/1jZSsY8QqS8HJBApXMzTGMtkKs6B5vstECIWpFMOg5io/edit#)

### General Tips

- [SCRF Research Improvement Proposal](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Proposal.md)
- [SCRF Research Improvement Process](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Process.md)

**Comment by ufkhan97** [comment]
Since our last update, we have:

- received three reviews on our first paper
- advanced those reviews to the metareviewer
- begun scheduling interviews for mid-september with reviewers 
- met with a prospective researcher for a second trial
- drafted additional potential peer review strategies
  - [Forum Review Timeline Options](https://docs.google.com/presentation/d/1HBFMaVFfXkLxYEqB3DNJydVSy6RDjtaGjEk8-i2qY9o/edit?usp=sharing )
  - [Scout Model](https://docs.google.com/presentation/d/1HBFMaVFfXkLxYEqB3DNJydVSy6RDjtaGjEk8-i2qY9o/edit?usp=sharing)
  - [Open Bounty Board Model](https://docs.google.com/document/d/1625uvGvlcvt6NWexmrr2ydUHeJt2giziFsBzkzoDDMM/edit)
