### ISSUE TITLE
Project: ACM Digital Threats Special Edition Editing/PM

### ISSUE THREAD

**Issue by eleventh19** [smartcontractresearchforum/operations#42]
### Project Description

This project is about helping create an ACM Digital Threats: Research and Practice Special Issue on blockchain. That would entail:
1) putting together a call for proposal
2) marketing to our network (and ACM does the same)
3) review submissions and peer review articles
4) publish issue
[Special Issue Editors.pdf](https://github.com/smartcontractresearchforum/research_team/files/6535311/Special.Issue.Editors.pdf)
[Examples of call for papers](https://dl.acm.org/journal/dtrap/calls-for-papers)

The benefit to SCRF is:
1) giving researchers we want to work with more a chance to publish some of their recent work (supporting outreach, new engagement opportunity, promotes research) 
2) provide SCRF a chance to create a follow up discussion to the issue on SCRF (drive additional engagement and content)
3) create more outreach opportunities to bring in more researchers 

### Work Plan

*Enter the steps as reflected in your Work Plan:*

- [x] create project doc
- [x] create process doc 
- [x] review the requirements and think through potential benefits
- [ ] decide if we want to do this
- [ ] identify a lead
- [ ] identify a few peer reviewers (at least 1-2 others)
- [ ] let ACM know
- [ ] put together a tenative timeline 
- [ ] draft the call for proposals 
- [ ] finalize the CFP
- [ ] create a plan of where to share the CFP
- [ ] review submissions
- [ ] reviewers meet to discuss? 
- [ ] work with ACM to put together issue
- [ ] do we need an engagement plan for when the special issue comes out? 

### Resources

- [link to project plan](https://docs.google.com/document/d/19yrYGEoTJ_1Z4obUOlfo5YWIOrCW2NkLrKb8Mo01mVw/edit?usp=sharing)
- See attached pdf that the editor-in-chief shared 

### General Tips

- [SCRF Research Improvement Proposal](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Proposal.md)
- [SCRF Research Improvement Process](https://github.com/smartcontractresearchforum/research_team/blob/main/docs/SCRF_Research_Improvement_Process.md)

### Updates

5/24/21 
Created issue, updated project doc. Will discuss with Rich on 5/25/21

**Comment by eleventh19** [comment]
This fell off the radar for a bit with other priorities that came up. Need to ping Leigh and revisit
